import keyboard, time
keyboard.send("windows+r")
time.sleep(0.5)
keyboard.write("notepad", delay=0.1)
keyboard.send('enter')
time.sleep(0.5)
keyboard.write("I will kill you!! :|\n\n")
time.sleep(0.5)
keyboard.write("( ¬ ‿¬)\n\n")
time.sleep(0.5)
keyboard.write("( ಠ◡ಠ )\n\n")
time.sleep(0.5)
keyboard.write("Extracting data!!.......\n\n",)
time.sleep(0.5)
keyboard.write("struct group_info init_groups = { .usage = ATOMIC_INIT(2) };", delay = 0.01)
time.sleep(0.5)
keyboard.write("\n\nConnecting to server {maaz hacking portal@123}!!......\n\n", delay = 0.1)
time.sleep(0.5)
keyboard.write("Data Sent.....\n\n", delay = 0.0523)
time.sleep(0.5)
keyboard.write("Good Bye !!\n\n", delay = 0.0523)
time.sleep(0.5)
keyboard.send("alt+F4")
keyboard.send('enter')
time.sleep(1)
keyboard.write("hacker.txt")
keyboard.send('enter')
time.sleep(1)
keyboard.send('enter')
time.sleep(1)
keyboard.send('enter')

